FROM ey3ball/nzbget-env:%TARGET%

RUN sed -i 's/restricted$/restricted multiverse/' /etc/apt/sources.list && \
        apt-get update -q && \
        apt-get install -qy ${NZBGET_RUNDEPS} && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*

ADD build/ /
ADD nzbget-entry.sh /usr/bin/nzbget-entry.sh

VOLUME ["/nzbget"]
EXPOSE 6789

CMD [ "--server" ]
ENTRYPOINT ["/usr/bin/nzbget-entry.sh"]
