FROM ubuntu:latest

ENV VERSION 15.0
ENV REVISION 1207

ENV NZBGET_FILE nzbget-${VERSION}-testing-r${REVISION}
ENV NZBGET_EXTDIR nzbget-${VERSION}-testing

ENV NZBGET_BUILDDEPS build-essential pkg-config  libxml2-dev libncurses5-dev \
                        libsigc++-2.0-dev libssl-dev
ENV NZBGET_RUNDEPS libxml2 libncurses5 libsigc++-2.0-0c2a libssl1.0.0 p7zip unrar
